{ pkgs, lib, ... }: {
  home.packages =
    with pkgs;
    [
      _1password-cli
      atac
      bash-language-server
      bear
      bottom
      buf
      clang-tools
      claude-code
      cloc
      clusterctl
      crane
      curl
      deno
      erdtree
      eza
      fastfetch
      fd
      ffmpeg
      fx
      fzf
      fzy
      gdu
      gh
      gnumake
      gnused
      go
      gopls
      helix
      helm-ls
      htop
      hwatch
      iftop
      inetutils
      ipcalc
      jdk
      jj
      jq
      just
      k6
      kind
      kubectl
      kubernetes-helm
      lima
      llvm
      lua
      lua-language-server
      mosh
      nixd
      nixfmt
      nmap
      nodejs
      openvpn
      podlet
      podman
      prettierd
      procs
      pyright
      python3
      qemu
      rip2
      ripgrep
      ripgrep-all
      ruff
      rustup
      shfmt
      skopeo
      stylua
      taplo
      tcpdump
      tealdeer
      tokei
      typescript-language-server
      uv
      wget
      xh
      yaml-language-server
      zig
    ]
    ++ lib.optionals pkgs.stdenv.hostPlatform.isDarwin [
      container
      iproute2mac
      mas
    ];

  xdg.configFile."npm/npmrc".text = ''
    prefix=''${XDG_DATA_HOME}/npm
    cache=''${XDG_CACHE_HOME}/npm
    init-module=''${XDG_CONFIG_HOME}/npm/config/npm-init.js
    logs-dir=''${XDG_STATE_HOME}/npm/logs
  '';
}
